#!/bin/bash
emfun() {
rm -rf b_$1
cp -R b b_$1
echo $1 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo $1 > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
./benchmark rovio 4 LLL LL partition6_amp 1
./benchmark rovio 4 LLL LB partition6_amp 1
./benchmark rovio 4 LLL BL partition6_amp 1
./benchmark rovio 4 LLL BB partition6_amp 1

cp tcomp32*.csv b_$1/tcomp32
cp lz4*.csv b_$1/lz4
cp tdic32*.csv b_$1/tdic32
}
emfun2() {
rm -rf b_$1
cp -R b b_$1
./tony_cpu set 0 1416000
./tony_cpu set 4 $1
./benchmark rovio 4 LLL LL partition6_amp 1
./benchmark rovio 4 LLL LB partition6_amp 1
./benchmark rovio 4 LLL BL partition6_amp 1
./benchmark rovio 4 LLL BB partition6_amp 1

cp tcomp32*.csv b_$1/tcomp32
cp lz4*.csv b_$1/lz4
cp tdic32*.csv b_$1/tdic32
}
#emfun2 1800000
#emfun2 1608000
emfun conservative
emfun ondemand
#emfun 1008000
#emfun 816000 

#emfun 50


    

