#!/bin/bash
emfun() {
rm -rf b_$1
cp -R b b_$1
./benchmark $1 4 LLL LL partition6_amp 1
./benchmark $1 4 LLL LB partition6_amp 1
./benchmark $1 4 LLL BL partition6_amp 1
./benchmark $1 4 LLL BB partition6_amp 1
cp tcomp32*.csv b_$1/tcomp32
cp lz4*.csv b_$1/lz4
cp tdic32*.csv b_$1/tdic32
}
emfun r_0.bin
emfun r_05.bin
emfun r_1.bin
emfun r_2.bin
#emfun 50


    

