#!/bin/bash
emfun() {
./benchmark rand1k_10 4 LLL LL partition6_amp $1
./benchmark rand1k_10 4 LLL LB partition6_amp $1
./benchmark rand1k_10 4 LLL BL partition6_amp $1
./benchmark rand1k_10 4 LLL BB partition6_amp $1
}
emfun 1
emfun 2
emfun 5
emfun 10
emfun 20
#emfun 50
cp tcomp32*.csv b/tcomp32
cp lz4*.csv b/lz4
    

