#!/bin/bash
emfun() {
rm -rf b_ar_$1
cp -R b b_ar_$1
rm *.csv
./benchmark randAll_10 4 LLL LL partition6_amp $1
./benchmark randAll_10 4 LLL LB partition6_amp $1
./benchmark randAll_10 4 LLL BL partition6_amp $1
./benchmark randAll_10 4 LLL BB partition6_amp $1

cp tdic32_feed*.csv b_ar_$1/e2
cp tdic32_pipe3*.csv b_ar_$1/e3
}
emfun 2000
emfun 5000
emfun 10000
emfun 20000
emfun 30000
emfun 40000

#emfun 50


    

