#!/bin/bash
emfun() {
./benchmark $1 4 LLL LL partition6_amp 1
./benchmark $1 4 LLL LB partition6_amp 1
./benchmark $1 4 LLL BL partition6_amp 1
./benchmark $1 4 LLL BB partition6_amp 1
cp tcomp32*.csv b_$1/tcomp32
cp lz4*.csv b_$1/lz4
cp tdic32*.csv b_$1/tdic32
}
emfun r32_1e4
emfun r32_1e6
emfun r32_1e7
emfun r32_1e8
#emfun 50


    

